name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure CMake
        run: cmake -B build -S .

      - name: Build
        run: cmake --build build --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: pennyunpacker-windows
          path: build/Release/pennyunpacker.exe
  linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure CMake
        run: cmake -B build -S .

      - name: Build
        run: cmake --build build --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: pennyunpacker-linux
          path: build/pennyunpacker
